#!/bin/bash
current_dir=`dirname "$BASH_SOURCE"`
if [ "$current_dir" = "." ]; then
    current_dir="$(pwd)"
fi
cd "$current_dir"
sudo su -c "
ifconfig lo:169 169.254.169.254 netmask 255.255.255.255 up
iptables -t nat -D OUTPUT -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 169.254.169.254:12319
iptables -t nat -I OUTPUT -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 169.254.169.254:12319
"
./bin/aws-cred-svc-linux
